export const SETTINGS = {
  className: "9-E",
  schoolName: "UPT SMPN 18 GRESIK",
  academicYear: "2023-2026",
  classLogo: "https://files.catbox.moe/qsajsp.jpg",
  schoolLogo: "https://files.catbox.moe/9e2ivs.png",
  schoolPhoto: "https://files.catbox.moe/qsajsp.jpg",
  developer: {
    name: "Defandryan",
    url: "https://defandryan.xte.web.id",
    vipId: 7
  },
  externalLinks: {
    xte: "https://xte.web.id",
    depstore: "https://defandryan.xte.web.id",
    school: "https://www.uptsmpn18gresik.sch.id"
  },
  structure: {
    waliKelas: { name: "Miss silvi", role: "Wali Kelas" },
    ketuaKelas: { name: "Hesti", role: "Ketua Kelas" },
    wakilKetua: { name: "Wisnu", role: "Wakil Ketua" },
    sekretaris: { name: "Erga & Alex", role: "Sekretaris" },
    bendahara: { name: "Vika", role: "Bendahara" }
  },
  students: [
    { id: 1, name: "Abizar", parent: "Ropul", quote: "Quote Siswa 1", photo: "https://via.placeholder.com/400x500?text=Siswa+1", isDev: false },
    { id: 2, name: "Dannis", parent: "Anam", quote: "Quote Siswa 2", photo: "https://via.placeholder.com/400x500?text=Siswa+2", isDev: false },
    { id: 3, name: "Alex", parent: "Ubing", quote: "Quote Siswa 3", photo: "https://via.placeholder.com/400x500?text=Siswa+3", isDev: false },
    { id: 4, name: "Citra", parent: "Ari", quote: "Quote Siswa 4", photo: "https://via.placeholder.com/400x500?text=Siswa+4", isDev: false },
    { id: 5, name: "Angel", parent: "ludi", quote: "Quote Siswa 5", photo: "https://via.placeholder.com/400x500?text=Siswa+5", isDev: false },
    { id: 6, name: "Erga", parent: "sugeng", quote: "Quote Siswa 6", photo: "https://via.placeholder.com/400x500?text=Siswa+6", isDev: false },
    { id: 7, name: "Defandryan", parent: "Rahasia, soalnya saya developer", quote: "Building the future, one line of code at a time.", photo: "https://via.placeholder.com/400x500?text=Defan", isDev: true },
    { id: 8, name: "Wina", parent: "hisana", quote: "Quote Siswa 8", photo: "https://via.placeholder.com/400x500?text=Siswa+8", isDev: false },
    { id: 9, name: "Dika", parent: "Roni", quote: "Jangan coli", photo: "https://via.placeholder.com/400x500?text=Siswa+9", isDev: false },
    { id: 10, name: "Hesti", parent: "Hariyanto", quote: "Quote Siswa 10", photo: "https://via.placeholder.com/400x500?text=Siswa+10", isDev: false },
    { id: 11, name: "Fabiano", parent: "rahman", quote: "Quote Siswa 11", photo: "https://via.placeholder.com/400x500?text=Siswa+11", isDev: false },
    { id: 12, name: "Ferdika", parent: "togel", quote: "Quote Siswa 12", photo: "https://via.placeholder.com/400x500?text=Siswa+12", isDev: false },
    { id: 13, name: "Ghani", parent: "huda", quote: "Quote Siswa 13", photo: "https://via.placeholder.com/400x500?text=Siswa+13", isDev: false },
    { id: 14, name: "Jessy", parent: "bambang", quote: "Quote Siswa 14", photo: "https://via.placeholder.com/400x500?text=Siswa+14", isDev: false },
    { id: 15, name: "Khoirul", parent: "sukadi", quote: "Quote Siswa 15", photo: "https://via.placeholder.com/400x500?text=Siswa+15", isDev: false },
    { id: 16, name: "Sella", parent: "hari", quote: "Quote Siswa 16", photo: "https://via.placeholder.com/400x500?text=Siswa+16", isDev: false },
    { id: 17, name: "Vika", parent: "sulis", quote: "Quote Siswa 17", photo: "https://via.placeholder.com/400x500?text=Siswa+17", isDev: false },
    { id: 18, name: "Meva", parent: "edii 😂", quote: "Penting urip", photo: "https://via.placeholder.com/400x500?text=Siswa+18", isDev: false },
    { id: 19, name: "Ardan", parent: "hadi", quote: "Solikin", photo: "https://via.placeholder.com/400x500?text=Siswa+19", isDev: false },
    { id: 20, name: "Subhan", parent: "is", quote: "Quote Siswa 20", photo: "https://via.placeholder.com/400x500?text=Siswa+20", isDev: false },
    { id: 21, name: "Lia", parent: "Suis", quote: "Quote Siswa 21", photo: "https://via.placeholder.com/400x500?text=Siswa+21", isDev: false },
    { id: 22, name: "Nashwa", parent: "Wati", quote: "Quote Siswa 22", photo: "https://via.placeholder.com/400x500?text=Siswa+22", isDev: false },
    { id: 23, name: "Nizam", parent: "ginto", quote: "Ikan hiu makan tomat, di laut gada tomat", photo: "https://via.placeholder.com/400x500?text=Siswa+23", isDev: false },
    { id: 24, name: "Novi", parent: "kandek", quote: "Quote Siswa 24", photo: "https://via.placeholder.com/400x500?text=Siswa+24", isDev: false },
    { id: 25, name: "Silla", parent: "Nama Orang Tua 25", quote: "Quote Siswa 25", photo: "https://via.placeholder.com/400x500?text=Siswa+25", isDev: false },
    { id: 26, name: "Reyhana", parent: "Nama Orang Tua 26", quote: "Quote Siswa 26", photo: "https://via.placeholder.com/400x500?text=Siswa+26", isDev: false },
    { id: 27, name: "Rivera", parent: "Nama Orang Tua 27", quote: "Quote Siswa 27", photo: "https://via.placeholder.com/400x500?text=Siswa+27", isDev: false },
    { id: 28, name: "Riski", parent: "Solikin", quote: "hadii", photo: "https://via.placeholder.com/400x500?text=Siswa+28", isDev: false },
    { id: 29, name: "Saila", parent: "Nama Orang Tua 29", quote: "Quote Siswa 29", photo: "https://via.placeholder.com/400x500?text=Siswa+29", isDev: false },
    { id: 30, name: "Alika", parent: "samsul", quote: "Quote Siswa 30", photo: "https://via.placeholder.com/400x500?text=Siswa+30", isDev: false },
    { id: 31, name: "Sulthan", parent: "budi", quote: "Quote Siswa 31", photo: "https://via.placeholder.com/400x500?text=Siswa+31", isDev: false },
    { id: 32, name: "Wisnu", parent: "eko", quote: "Quote Siswa 32", photo: "https://via.placeholder.com/400x500?text=Siswa+32", isDev: false }
  ],
  gallery: {
    fotoKelas: [
      "https://via.placeholder.com/800x600?text=Foto+Kelas+1",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+2",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+3",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+4",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+5",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+6",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+7",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+8",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+9",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+10",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+11",
      "https://via.placeholder.com/800x600?text=Foto+Kelas+12"
    ],
    fotoAib: [
      "https://via.placeholder.com/400x400?text=Aib+1", "https://via.placeholder.com/400x400?text=Aib+2",
      "https://via.placeholder.com/400x400?text=Aib+3", "https://via.placeholder.com/400x400?text=Aib+4",
      "https://via.placeholder.com/400x400?text=Aib+5", "https://via.placeholder.com/400x400?text=Aib+6",
      "https://via.placeholder.com/400x400?text=Aib+7", "https://via.placeholder.com/400x400?text=Aib+8",
      "https://via.placeholder.com/400x400?text=Aib+9", "https://via.placeholder.com/400x400?text=Aib+10",
      "https://via.placeholder.com/400x400?text=Aib+11", "https://via.placeholder.com/400x400?text=Aib+12",
      "https://via.placeholder.com/400x400?text=Aib+13", "https://via.placeholder.com/400x400?text=Aib+14",
      "https://via.placeholder.com/400x400?text=Aib+15", "https://via.placeholder.com/400x400?text=Aib+16",
      "https://via.placeholder.com/400x400?text=Aib+17", "https://via.placeholder.com/400x400?text=Aib+18",
      "https://via.placeholder.com/400x400?text=Aib+19", "https://via.placeholder.com/400x400?text=Aib+20",
      "https://via.placeholder.com/400x400?text=Aib+21", "https://via.placeholder.com/400x400?text=Aib+22",
      "https://via.placeholder.com/400x400?text=Aib+23", "https://via.placeholder.com/400x400?text=Aib+24",
      "https://via.placeholder.com/400x400?text=Aib+25", "https://via.placeholder.com/400x400?text=Aib+26",
      "https://via.placeholder.com/400x400?text=Aib+27", "https://via.placeholder.com/400x400?text=Aib+28",
      "https://via.placeholder.com/400x400?text=Aib+29", "https://via.placeholder.com/400x400?text=Aib+30",
      "https://via.placeholder.com/400x400?text=Aib+31", "https://via.placeholder.com/400x400?text=Aib+32",
      "https://via.placeholder.com/400x400?text=Aib+33", "https://via.placeholder.com/400x400?text=Aib+34",
      "https://via.placeholder.com/400x400?text=Aib+35", "https://via.placeholder.com/400x400?text=Aib+36",
      "https://via.placeholder.com/400x400?text=Aib+37", "https://via.placeholder.com/400x400?text=Aib+38",
      "https://via.placeholder.com/400x400?text=Aib+39", "https://via.placeholder.com/400x400?text=Aib+40"
    ],
    fotoKenangan: [
      "https://via.placeholder.com/1280x720?text=Kenangan+1",
      "https://via.placeholder.com/1280x720?text=Kenangan+2",
      "https://via.placeholder.com/1280x720?text=Kenangan+3",
      "https://via.placeholder.com/1280x720?text=Kenangan+4",
      "https://via.placeholder.com/1280x720?text=Kenangan+5",
      "https://via.placeholder.com/1280x720?text=Kenangan+6",
      "https://via.placeholder.com/1280x720?text=Kenangan+7",
      "https://via.placeholder.com/1280x720?text=Kenangan+8",
      "https://via.placeholder.com/1280x720?text=Kenangan+9",
      "https://via.placeholder.com/1280x720?text=Kenangan+10",
      "https://via.placeholder.com/1280x720?text=Kenangan+11",
      "https://via.placeholder.com/1280x720?text=Kenangan+12",
      "https://via.placeholder.com/1280x720?text=Kenangan+13",
      "https://via.placeholder.com/1280x720?text=Kenangan+14",
      "https://via.placeholder.com/1280x720?text=Kenangan+15"
    ]
  }
};
